# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    target-branch: "dev"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
    allow:
      # Allow direct updates only for all packages
      - dependency-type: "direct"
    commit-message:
      prefix: "dep: "  
