export const ContentFlow = {
    Name: ``,
    GroupName:``,
    SourceTypeCSV:`CSV`,
    GenerativeModel: `Google Gemini Pro 1.0`,
    GenerativeModelBase: 'Google Gemini Pro 1.0base',
    ExtraPrompt: 'ExtraPrompt',
    MaxTokens: `55`,
    ProductId: `id`,
    Template: "Blank",
    Language: "English",
    MandatoryKeyword: "MandatoryKeyword",
    BannedKeyword: "BannedKeyword",
    MandatoryKeywordEN: "MandatoryKeyword (EN)",
    BannedKeywordEN: "BannedKeyword (EN)",
    StatusNA: "N/A",
    Availability: "Inactive",
    Url: "https://storage.googleapis.com/trustgen-source-feed-samples/nike-menshoes-samples_10p.csv",
    Week: "false",
    Manual: "true",
    Month: "false",
}

export const UpdateContentFlow = {
    Name: ``,
    OldName: ``,
    GroupName:``,
    SourceTypeCSV:`CSV`,
    GenerativeModel: `ChatGPT 3.5 Turbo`,
    GenerativeModelBase: 'ChatGPT 3.5 Turbobase',
    ExtraPrompt: 'UpdatedExtraPrompt',
    MaxTokens: `66`,
    ProductId: `id`,
    ProductColor: `color`,
    ProductBrand: `brand`,
    ProductType: `product_type`,
    ProductTittle: `tittle`,
    Template: "Default",
    Language: "Spanish",
    MandatoryKeyword: "UpdateMandatoryKeyword",
    BannedKeyword: "UpdateBannedKeyword",
    MandatoryKeywordEN: "UpdateMandatoryKeyword (EN)(ES)",
    BannedKeywordEN: "UpdateBannedKeyword (EN)(ES)",
    StatusNA: "N/A",
    StatusRunning: "Running",
    StatusSucceeded: "Succeeded",
    Availability: "Inactive",
    AvailabilityFailed: "Failed",
    AvailabilityActive: "Active",
    Url: "https://storage.googleapis.com/trustgen-source-feed-samples/nike-menshoes-samples_10p.csv",
    Week: "true",
    Manual: "false",
    Month: "false",
    Empty: " - ",
    EmptyValue: "-",
    Metrics: "10",
    HITLOn: "HITL On",
}